### ISSUE TITLE
WeuiTopTips & toast 如何配合axios使用?

### ISSUE THREAD

**Issue by xiexiangrui** [llkui/weui-design-vue#3]
`  
import axios from 'axios';
import { WeuiTopTips } from 'weui-design-vue';

service.interceptors.response.use((res) => {
  // 获取错误信息
  const msg = res.data.msg || '';
  WeuiTopTips.show('test');
  
  return res.data;
}, (error) => {
  let { message } = error;
  WeuiTopTips.show(message);
  return Promise.reject(error);
});
// 提示 WeuiTopTips.show is not a function
WeuiTopTips.show('test');

`

**Comment by llkui** [comment]
main.js中可以使用Vue实例
`const app = new Vue({
  router,
  render: h => h(App)
}).$mount('#app')`
将
`WeuiTopTips.show('test');`
替换为
`app.$toptips.show('test');`

**Comment by xiexiangrui** [comment]
> main.js中可以使用Vue实例
> `const app = new Vue({ router, render: h => h(App) }).$mount('#app')`
> 将
> `WeuiTopTips.show('test');`
> 替换为
> `app.$toptips.show('test');`

我不是在main.js 里面的，其实内容是在 /src/util/request.js
能有啥办法用吗

**Comment by llkui** [comment]
在/src/util/request.js文件中，引入Vue
`import Vue from 'vue'`
将
`WeuiTopTips.show('test');`
替换为
`Vue.prototype.$toptips.show('test');`

**Comment by xiexiangrui** [comment]
> 在/src/util/request.js文件中，引入Vue
> `import Vue from 'vue'`
> 将
> `WeuiTopTips.show('test');`
> 替换为
> `Vue.prototype.$toptips.show('test');`

嗯， 感谢 ， 确实可以这么用
