### ISSUE TITLE
为什么在dark 模式下,样式适配有问题

### ISSUE THREAD

**Issue by xiexiangrui** [llkui/weui-design-vue#5]
例如 cell里面的title ， dialog 里面的title
![image](https://i.bmp.ovh/imgs/2021/04/7f0cec8e1b1c93f6.png)

**Comment by llkui** [comment]
怎么复现的？
我在浏览器选择暗黑模式和example中主动切换到暗黑模式，都没有问题
![1617851863(1)](https://user-images.githubusercontent.com/16408591/113963753-c4236800-985c-11eb-90e0-f2ad77a2cc50.jpg)
![1617851911(1)](https://user-images.githubusercontent.com/16408591/113963798-d7363800-985c-11eb-8476-1d277a973814.jpg)

**Comment by xiexiangrui** [comment]
> 怎么复现的？
> 我在浏览器选择暗黑模式和example中主动切换到暗黑模式，都没有问题
> ![1617851863(1)](https://user-images.githubusercontent.com/16408591/113963753-c4236800-985c-11eb-90e0-f2ad77a2cc50.jpg)
> ![1617851911(1)](https://user-images.githubusercontent.com/16408591/113963798-d7363800-985c-11eb-8476-1d277a973814.jpg)

windows  直接切换系统为深色模式
我自己项目手动切换dark 模式  cell 有问题 ，dialog 有问题 
`
async created() {
    this.dialog.show = true;
    const body = document.getElementsByTagName('body')[0];
    body.setAttribute('data-weui-theme', 'dark');
    body.style.backgroundColor = '#111';
  
 },
`
在你这边项目文档 我是直接切换window 为暗色模式，就出现这个问题了 
还有各种按钮也看不清了

**Comment by llkui** [comment]
没有适配系统的深色模式，看上去会有些乱。

暂时优化了一下组件在深色模式下的样式，文档中的其他内容会在后续逐步优化

**Comment by xiexiangrui** [comment]
https://www.npmjs.com/package/weui-design-vue
可以更新发布下么？现在在用着

**Comment by llkui** [comment]
这个和组件库无关，只是项目外层样式的应用，你可以看一下我的最新提交记录，在你项目中，稍作调整就可以了。
主要涉及到color和background-color的调整
![1617888763(1)](https://user-images.githubusercontent.com/16408591/114036324-8fda9680-98b2-11eb-8bd5-c97e20e8a15e.jpg)
